.\" Manpage for apkinfo.
.\" Contact wearecisco@gmail.com to correct errors or typos.
.TH man 8 "10 May 2017" "0.0.1" "apkinfo man page"
.SH NAME
apkinfo \- A command what to look up a apk info, that include meta-data applicationid versioncode versionname etc.
.SH SYNOPSIS
apkinfo [APK_FILE]
.SH DESCRIPTION
apkinfo what to look up a apk info, that include meta-data applicationid versioncode versionname etc.
.SH OPTIONS
.TP
.PD 0
.BI \-h
.TP
.PD
.B \-\-help
show help and xxx
.SH SEE ALSO

.SH BUGS
No known bugs.
.SH AUTHOR
DavidZou (wearecisco@gmail.com)